# This file contains values from Cookiecutter

default_context:
  project_name: "shopback-sdk"
  project_description: "shopback.ru - no code shop constructor and cafe for telegram"
  organization: "ktsstudio"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "ktsstudio"
  email: "hello@ktsstudio.com"
  version: "0.1.0"
  line_length: "100"
  create_example_template: "none"
